# Generated by Django 5.2.4 on 2025-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapoverlay',
            name='permission_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
