# Generated by Django 5.2.4 on 2025-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
