# Generated by Django 6.0 on 2025-12-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_remove_namedgeoreferenceditem_symbol_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedgeoreferenceditem',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='namedgeoreferenceditem',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
