# Generated by Django 6.0 on 2025-12-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_namedgeoreferenceditem_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedgeoreferenceditem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namedgeoreferenceditem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
