# Generated by Django 5.2.4 on 2025-07-17 22:35

import objects.takzeichen_types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_mapicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapicon',
            name='icon',
        ),
        migrations.AddField(
            model_name='mapicon',
            name='einheit',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_einheits_types, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='fachaufgabe',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_fachaufgaben_types, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='farbe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='funktion',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_funktion_types, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='grundzeichen',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_grundzeichen_types, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='organisation',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_organisation_types, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='organisationName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='symbol',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_symbol_types, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='typ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapicon',
            name='verwaltungsstufe',
            field=models.CharField(blank=True, choices=objects.takzeichen_types.get_verwaltungsstufen_types, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mapicon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
