# Generated by Django 6.0 on 2025-12-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_namedgeoreferenceditem_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
