# Generated by Django 6.0 on 2025-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_unit_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
