# Generated by Django 5.2.4 on 2025-07-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_remove_mapicon_icon_mapicon_einheit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapicon',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mapicon',
            name='name',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
    ]
