# Generated by Django 6.0 on 2025-12-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_unit_unit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='group',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='show_on_map',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='zoom_level',
        ),
    ]
