# Generated by Django 5.2.4 on 2025-07-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_mapicon_icon_name_alter_mapicon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapicon',
            old_name='organisationName',
            new_name='organisation_name',
        ),
    ]
