# Generated by Django 6.0 on 2025-12-29 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_remove_unit_group_remove_unit_show_on_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='speak_request',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(editable=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='objects.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
