# Generated by Django 6.0 on 2025-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_unit_speak_request_unitstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitstatus',
            name='status',
            field=models.IntegerField(),
        ),
    ]
