# Generated by Django 6.0 on 2025-12-29 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_unit_unit_status_timestamp_alter_unitstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedgeoreferenceditem',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnitLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='objects.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
