# Generated by Django 6.0 on 2025-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_namedgeoreferenceditem_location_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
